package kz.synapse.models;

import kz.synapse.database.Database;
import kz.synapse.enums.*;
import java.util.Comparator;
import java.util.List;
import java.util.stream.Collectors;

public abstract class Manager extends Employee {

    private ManagerType type;

    public Manager(String id, String name, String email,
                   String password, Language language,
                   double salary, ManagerType type) {
        super(id, name, email, password, language, salary);
        this.type = type;
    }

    public ManagerType getType() { return type; }


    public void approveRegistration(CourseRegistration r) {
        r.approve();
        r.getStudent().getEnrolledCourses().add(r.getCourse());
        r.getStudent().setCredits(
                r.getStudent().getCredits() + r.getCourse().getCredits()
        );
        logAction("Approved: " + r.getStudent().getName()
                + " → " + r.getCourse().getName());
    }

    public void rejectRegistration(CourseRegistration r) {
        r.reject();
        r.getStudent().getNotifications().add(
                new Notification("Registration rejected: "
                        + r.getCourse().getName())
        );
        logAction("Rejected: " + r.getStudent().getName()
                + " → " + r.getCourse().getName());
    }

    public List<CourseRegistration> viewPendingRegistrations() {
        return Database.getInstance().getPendingRegistrations()
                .stream()
                .filter(r -> r.getStatus() == RegistrationStatus.PENDING)
                .collect(Collectors.toList());
    }

    public List<Student> viewStudents(Comparator<Student> c) {
        return Database.getInstance().getAllStudents()
                .stream()
                .sorted(c)
                .collect(Collectors.toList());
    }

    public List<Teacher> viewTeachers(Comparator<Teacher> c) {
        return Database.getInstance().getAllTeachers()
                .stream()
                .sorted(c)
                .collect(Collectors.toList());
    }

    public List<EmployeeRequest> viewSignedEmployeeRequests() {
        List<EmployeeRequest> signed = Database.getInstance()
                .getEmployeeRequests()
                .stream()
                .filter(EmployeeRequest::isSignedByDean)
                .collect(Collectors.toList());

        logAction("Viewed signed employee requests");
        return signed;
    }

    public String createPerformanceReport() {
        List<Student> students = Database.getInstance().getAllStudents();
        double avgGpa = students.stream()
                .mapToDouble(Student::getGpa)
                .average()
                .orElse(0.0);
        return "--- PERFORMANCE REPORT ---\n"
                + "Total Students: " + students.size() + "\n"
                + "Average GPA: " + String.format("%.2f", avgGpa) + "\n"
                + "Generated by: " + getName();
    }

    @Override
    public String toString() {
        return String.format("Manager{name='%s', email='%s'}",
                getName(), getEmail());
    }
}