package kz.synapse.models;

import kz.synapse.database.Database;
import kz.synapse.enums.*;

import java.util.Comparator;
import java.util.List;
import java.util.stream.Collectors;

public abstract class Manager extends Employee {

    private static final long serialVersionUID = 1L;

    private final ManagerType type;

    public Manager(String id, String name, String email,
                   String password, Language language,
                   ManagerType type) {
        super(id, name, email, password, language);
        this.type = type;
    }

    public ManagerType getType() { return type; }

    public void approveRegistration(CourseRegistration r) {
        r.approve();
        Student student  = r.getStudent();
        CourseOffering o = r.getOffering();

        o.enrollStudent(student);
        student.enrollInOffering(o);

        Database.getInstance().removePendingRegistration(r);
        Database.getInstance().addApprovedRegistration(r);

        logAction("Approved: " + student.getName() + " → " + o.getCourse().getName());
    }

    public void rejectRegistration(CourseRegistration r) {
        r.reject();
        r.getStudent().addNotification(
                new Notification("Registration rejected: "
                        + r.getOffering().getCourse().getName()));

        Database.getInstance().removePendingRegistration(r);

        logAction("Rejected: " + r.getStudent().getName()
                + " → " + r.getOffering().getCourse().getName());
    }

    public List<CourseRegistration> viewPendingRegistrations() {
        return Database.getInstance().getPendingRegistrations().stream()
                .filter(r -> r.getStatus() == RegistrationStatus.PENDING)
                .collect(Collectors.toList());
    }

    // просмотр людей

    public List<Student> viewStudents(Comparator<Student> c) {
        return Database.getInstance().getAllStudents().stream()
                .sorted(c).collect(Collectors.toList());
    }

    public List<Teacher> viewTeachers(Comparator<Teacher> c) {
        return Database.getInstance().getAllTeachers().stream()
                .sorted(c).collect(Collectors.toList());
    }

    // employee Requests

    public List<EmployeeRequest> viewSignedEmployeeRequests() {
        logAction("Viewed signed employee requests");
        return Database.getInstance().getEmployeeRequests().stream()
                .filter(EmployeeRequest::isSignedByDean)
                .collect(Collectors.toList());
    }

    // отчёт об успеваемости

    public String createPerformanceReport() {
        List<Student> students = Database.getInstance().getAllStudents();
        double avgGpa = students.stream()
                .mapToDouble(Student::getGpa).average().orElse(0.0);
        logAction("Created performance report");
        return "--- UNIVERSITY PERFORMANCE REPORT ---\n"
                + "Total Students: " + students.size() + "\n"
                + "Average GPA:    " + String.format("%.2f", avgGpa) + "\n"
                + "Generated by:   " + getName();
    }


    public void addNews(String title, String content, NewsType newsType) {
        News news = new News(title, content, newsType);
        Database.getInstance().addNews(news);
        logAction("Published news: " + title);
    }

    public void removeNews(News news) {
        Database.getInstance().removeNews(news);
        logAction("Removed news: " + news.getTitle());
    }

    public void pinNews(News news) {
        news.setPinned(true);
        logAction("Pinned news: " + news.getTitle());
    }

    public void unpinNews(News news) {
        news.setPinned(false);
        logAction("Unpinned news: " + news.getTitle());
    }

    @Override
    public String toString() {
        return String.format("Manager{name='%s', type=%s}", getName(), type);
    }
}
